
services:
  backend:
    build: ./backend
    container_name: platform_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/platform_db
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    working_dir: /app

  celery_worker:
    build: ./backend
    container_name: platform_celery_worker
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/platform_db
    depends_on:
      - redis
      - postgres
    volumes:
      - ./backend:/app
    working_dir: /app
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A app.celery_app worker --loglevel=info

  postgres:
    image: postgres:15
    container_name: platform_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: platform_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: platform_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: