version: '3.8'

services:
  backend:
    build: ./backend
    container_name: platform_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/platform_db
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    working_dir: /app

  postgres:
    image: postgres:15
    container_name: platform_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: platform_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: platform_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: