"""create_generation_jobs_table

Revision ID: c0c1cac606dc
Revises: ca6da0775e93
Create Date: 2025-08-13 11:10:39.552820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c1cac606dc'
down_revision = 'ca6da0775e93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('run_id', sa.String(length=255), nullable=True),
    sa.Column('pr_url', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generation_jobs_owner_id', 'generation_jobs', ['owner_id'])
    op.create_index('ix_generation_jobs_status', 'generation_jobs', ['status'])
    op.create_index('ix_generation_jobs_created_at', 'generation_jobs', ['created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generation_jobs_created_at', table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_status', table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_owner_id', table_name='generation_jobs')
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###